# Generated by Django 4.2.30 on 2026-05-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2000, verbose_name='Оригинальный URL')),
                ('short_code', models.CharField(max_length=50, unique=True, verbose_name='Короткий код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('clicks_count', models.IntegerField(default=0, verbose_name='Количество переходов')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='Последний переход')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
