# Generated by Django 4.2.30 on 2026-06-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_code',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Короткий код'),
        ),
    ]
